added styles and image for car
relectric-car-team/user-interface pull request #30
Opened 2021-03-02 03:47 UTC by thomaskahessay

Not 100% sure if I did this correctly, but that's what reviews are for 😃

2021-03-02 03:53 UTC, RatikKapoor commented on src/pages/Car.tsx
> +                <IonToolbar color="#099648" className="CarToolBar">
Good job on using Ionic components!

2021-03-02 19:51 UTC, elizetran approved these changes
🚗 beep beep 🚙

2021-03-16 21:09 UTC, b4yc approved these changes
Looks good :)

2021-03-16 21:11 UTC, RatikKapoor requested changes
Will chat in meeting today

2021-03-16 23:19 UTC, closed without merging