Updated the icons for the buttons, created a new page called "setting…
relectric-car-team/user-interface pull request #9
Opened 2020-12-27 23:22 UTC by brooke-k

…s" to house the settings and linked it to the tab bar. Had to update the typescript to the latest version to allow the app to open, but no other problems.

2020-12-27 23:35 UTC, RatikKapoor requested changes
Can you remove `package-lock.json` and use `yarn install` instead of `rpm install`? Having both `package-lock.json` and `yarn.lock` can get messy and break the build! @brooke-k

2020-12-28 04:37 UTC, brooke-k commented
Yep! Not sure how to add on to this pull request, if possible, so I'll close this and submit a new one with the updated changes.

2020-12-28 04:42 UTC, RatikKapoor approved these changes
:shipit:

2020-12-30 19:39 UTC, RatikKapoor commented
Whoops, accidentally removed my review. Fixing now

2020-12-30 19:40 UTC, RatikKapoor approved these changes
🚢

2020-12-31 21:31 UTC, b4yc commented on src/App.tsx
> +import { carOutline, musicalNoteOutline, navigateOutline, menuOutline } from 'ionicons/icons';
hehe awesome

2020-12-31 21:32 UTC, b4yc reviewed
:shipit:

2020-12-31 21:33 UTC, b4yc approved these changes

2020-12-31 21:33 UTC, merged